### PR TITLE
Update MISC line for FDS level set cases

### PR DESCRIPTION
**Pull request by mcgratta**

### CODE REVIEW

**Comment by mcgratta** [comment]
I do not understand why there is a conflict. Could it be line endings? The comparison of old and new files does not indicate a problem.

**Comment by mcgratta** [comment]
I guess I resolved the problem

**Comment by mcgratta** [comment]
I think I forgot to update my local repo or something like this. Ignore this PR and I'm going to start over.

**Comment by emanuelegissi** [comment]
Ok

**Pull request closed without merging**
